/* 
 * Xero Payroll AU
 *
 * This is the Xero Payroll API for orgs in Australia region.
 *
 * The version of the OpenAPI document: 2.2.2
 * Contact: api@xero.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Xero.NetStandard.OAuth2.Model.PayrollAu
{
    /// <summary>
    /// Defines SuperannuationCalculationType
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum SuperannuationCalculationType
    {
        /// <summary>
        /// Enum FIXEDAMOUNT for value: FIXEDAMOUNT
        /// </summary>
        [EnumMember(Value = "FIXEDAMOUNT")]
        FIXEDAMOUNT = 1,

        /// <summary>
        /// Enum PERCENTAGEOFEARNINGS for value: PERCENTAGEOFEARNINGS
        /// </summary>
        [EnumMember(Value = "PERCENTAGEOFEARNINGS")]
        PERCENTAGEOFEARNINGS = 2,

        /// <summary>
        /// Enum STATUTORY for value: STATUTORY
        /// </summary>
        [EnumMember(Value = "STATUTORY")]
        STATUTORY = 3

    }

}
